[package]
name = "tfs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.1"
dashmap = "6.1.0"
hostname = "0.4.0"
ibverbs = { git = "https://github.com/2022tgoel/rust-ibverbs" } 
ibverbs-sys = { git = "https://github.com/2022tgoel/rust-ibverbs" }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.1"
zeromq = "0.4.1"

[lib]
name = "tfs"
path = "src/lib.rs"

[[bin]]
name = "rdma_client"
path = "src/bin/rdma_test/client.rs"

[[bin]]
name = "rdma_server"
path = "src/bin/rdma_test/server.rs"

[[bin]]
name = "chunkserver"
path = "src/bin/chunkserver_test/server.rs"

[[bin]]
name = "client"
path = "src/bin/chunkserver_test/client.rs"
