[package]
name = "tfs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.1"
hostname = "0.4.0"
ibverbs = "0.9.2"
serde_json = "1.0.140"
tokio = "1.44.1"
zeromq = "0.4.1"
